architecture = { ...
    {'conv', 0, ps.conv_f11_p4_s4,  64,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 3, 2}; ...
    {'conv', 0, ps.conv_f5_p4_s1,  192,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 3, 2}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  384,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  256,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  256,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 3, 2}; ...
    {'adaptiveavgpool', 1}; ...
    {'fully_connected', 256*6*6, 4096, ps.act_float_relu}; ...
    {'fully_connected', 4096, 4096, ps.act_float_relu}; ...
    {'fully_connected', 4096, 1000, ps.act_linear_0_0_0}; ...
    {'softmax'};
    };