input_input_channels = 1;

architecture = { ...
    {'conv', 0, ps.conv_f5_p4_s1,   32,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', -1};
    {'conv', 0, ps.conv_f5_p4_s1,    8,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   32,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  0,   'relu'};                                                                                     
    
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 4};
    {'conv', 0, ps.conv_f1_p0_s1,    4,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  5,   'relu'};                                                                                     
    
    {'conv', 0, ps.conv_f3_p2_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 9};
    {'conv', 0, ps.conv_f3_p2_s1,    4,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  10,   'relu'};                                                                                    
    
    {'conv', 0, ps.conv_f3_p2_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 14};
    {'conv', 0, ps.conv_f3_p2_s1,    4,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  15,   'relu'};                                                                                    
    
    {'conv', 0, ps.conv_f3_p2_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 19};
    {'conv', 0, ps.conv_f3_p2_s1,    4,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  20,   'relu'};                                                                                    
    
    {'conv', 0, ps.conv_f3_p2_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 24};
    {'conv', 0, ps.conv_f3_p2_s1,    4,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   16,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  25,   'relu'};                                                                                    
    
    {'conv', 0, ps.conv_f1_p0_s1,   32,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'route', 29};
    {'conv', 0, ps.conv_f1_p0_s1,    8,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f1_p0_s1,   32,  ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'res',  30,   'relu'};                                                                                    
    
    {'conv', 0, ps.conv_f3_p2_s1,    4,  ps.act_linear_0_0_0, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'sr_flat'};
    {'lp_sres'};
};