% VGG architecture D
% "D": [64, 64, "M", 128, 128, "M", 256, 256, 256, "M", 512, 512, 512, "M", 512, 512, 512, "M"],
architecture = { ...
    {'conv', 0, ps.conv_f3_p2_s1,  64,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  64,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 2, 2}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  128,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  128,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 2, 2}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  256,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  256,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  256,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 2, 2}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 2, 2}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'conv', 0, ps.conv_f3_p2_s1,  512,   ps.act_float_relu, ps.wts_none, ps.scales_float, ps.biases_float}; ...
    {'maxpool', 2, 2}; ...
    {'adaptiveavgpool', 1}; ...
    {'fully_connected', 512 * 7 * 7, 4096, ps.act_float_relu}; ...
    {'fully_connected', 4096, 4096, ps.act_float_relu}; ...
    {'fully_connected', 4096, 1000, ps.act_linear_0_0_0}; ...
    {'softmax'};
    };